version: '3.3'
services:
  mongodb:
    image: mongo
    container_name: db-nida-app
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nida
      - MONGO_INITDB_ROOT_PASSWORD=nida
    ports:
      - 27017:27017
    volumes:
      - "D:/data/mongodb/nida-app:/db-data"

